stages:
  - build 
  - deploy

build:
  stage: build
  script:
    - docker --version
    - docker-compose --version
    - docker-compose build
  tags:
    - dev

deploy:
  stage: deploy
  script:
    - docker-compose up -d
