stages:
  - build 

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker --version
    - docker-compose --version
    - docker-compose build
  tags:
    - dev
