stages:
  - build 
  - deploy

build:
  stage: build
  script:
    - docker-compose build
    - cd backend
    - echo "SECRET_KEY=$SECRET_KEY" >> .env
    - echo "kakao_client_id=$kakao_client_id" >> .env
  artifacts:
    reports:
      dotenv: .env
  tags:
    - dev

deploy:
  stage: deploy
  script:
    # - docker-compose run backend python manage.py migrate
    - docker-compose up -d
  tags:
    - dev
