stages:
  - test
  - build 
  - deploy

test:
  stage: test
  image: python:3
  only:
    - tests@s06-ai-image-sub2/S06P22D102
    - develop@s06-ai-image-sub2/S06P22D102
  script:
    - pip install pytest pytest-cov
    - coverage run -m pytest
    - coverage report
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml
  tags:
    - dev

build:
  stage: build
  only:
    - develop@s06-ai-image-sub2/S06P22D102
  script:
    - docker-compose build
  tags:
    - dev

deploy:
  stage: deploy
  only:
    - develop@s06-ai-image-sub2/S06P22D102
  script:
    - docker-compose up -d
    - docker-compose run backend python manage.py migrate
  tags:
    - dev
