stages:
  - build 
  - deploy

build:
  stage: build
  script:
    - docker-compose build
    # - docker-compose run backend python manage.py migrate
  tags:
    - dev

deploy:
  stage: deploy
  script:
    - docker-compose run backend python manage.py migrate
    - docker-compose up -d
  tags:
    - dev
