version: "3"

services:
  db:
    image: mysql
    restart: always
    container_name: mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_PASSWORD=horang22
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - /tmp/slack_bot/mysqld:/run/mysqld
